import base64
import io
import os
import tempfile
from typing import Callable, Tuple, Coroutine

import subprocess
from docx import Document
from pdf2docx import Converter


def convert_pdf_to_docx(pdf_bytes: bytes) -> bytes:
    """
    Converts a PDF file (in bytes) to a DOCX file (in bytes) using pdf2docx.
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as pdf_file:
        pdf_file.write(pdf_bytes)
        pdf_path = pdf_file.name
        
    docx_path = pdf_path + ".docx"
    
    try:
        cv = Converter(pdf_path)
        cv.convert(docx_path)
        cv.close()
        
        with open(docx_path, "rb") as docx_file:
            docx_bytes = docx_file.read()
            
        return docx_bytes
    finally:
        if os.path.exists(pdf_path):
            try:
                os.remove(pdf_path)
            except Exception:
                pass
        if os.path.exists(docx_path):
            try:
                os.remove(docx_path)
            except Exception:
                pass

def convert_docx_to_pdf(docx_bytes: bytes) -> bytes:
    """
    Converts a DOCX file (in bytes) to a PDF file (in bytes) using LibreOffice.
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".docx") as docx_file:
        docx_file.write(docx_bytes)
        docx_path = docx_file.name
        
    outdir = os.path.dirname(docx_path)
    base_name = os.path.splitext(os.path.basename(docx_path))[0]
    pdf_path = os.path.join(outdir, f"{base_name}.pdf")
    
    try:
        # Run libreoffice headlessly
        subprocess.run([
            "libreoffice", "--headless", "--convert-to", "pdf", 
            "--outdir", outdir, docx_path
        ], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        
        if os.path.exists(pdf_path):
            with open(pdf_path, "rb") as pdf_file:
                return pdf_file.read()
        else:
            raise Exception("PDF file was not generated by LibreOffice.")
    finally:
        if os.path.exists(docx_path):
            try:
                os.remove(docx_path)
            except Exception:
                pass
        if os.path.exists(pdf_path):
            try:
                os.remove(pdf_path)
            except Exception:
                pass


async def translate_docx_document(
    file_bytes: bytes,
    translate_batch_fn: Callable[[list[str]], Coroutine[None, None, list[str]]]
) -> Tuple[str, str]:
    """
    Translates a DOCX document run by run, preserving the layout using batch translation.
    Returns:
        Tuple[str, str]: (all_translated_text, base64_encoded_docx)
    """
    doc = Document(io.BytesIO(file_bytes))
    
    paragraphs_to_process = []
    
    def collect_paragraph(paragraph):
        if paragraph.text.strip():
            paragraphs_to_process.append(paragraph)

    for paragraph in doc.paragraphs:
        collect_paragraph(paragraph)
            
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    collect_paragraph(paragraph)
                    
    if paragraphs_to_process:
        texts = [p.text for p in paragraphs_to_process]
        # Await the async translation function
        translated_texts = await translate_batch_fn(texts)
        
        for i, paragraph in enumerate(paragraphs_to_process):
            translated_clean = translated_texts[i] if i < len(translated_texts) else paragraph.text
            if not translated_clean:
                translated_clean = paragraph.text
            
            if paragraph.runs:
                # Capture the style of the first non-empty run if possible
                first_run = paragraph.runs[0]
                for r in paragraph.runs:
                    if r.text.strip():
                        first_run = r
                        break
                
                font_name = first_run.font.name
                font_size = first_run.font.size
                bold = first_run.font.bold
                italic = first_run.font.italic
                underline = first_run.font.underline
                color = None
                if first_run.font.color and first_run.font.color.rgb:
                    color = first_run.font.color.rgb
                
                # Clear all runs
                for run in paragraph.runs:
                    run.text = ""
                
                # Assign to the first run and restore font attributes
                paragraph.runs[0].text = translated_clean
                paragraph.runs[0].font.name = font_name
                paragraph.runs[0].font.size = font_size
                paragraph.runs[0].font.bold = bold
                paragraph.runs[0].font.italic = italic
                paragraph.runs[0].font.underline = underline
                if color:
                    paragraph.runs[0].font.color.rgb = color
            else:
                paragraph.add_run(translated_clean)

    all_translated_texts = []
    for paragraph in doc.paragraphs:
        if paragraph.text.strip():
            all_translated_texts.append(paragraph.text.strip())
            
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    if paragraph.text.strip():
                        all_translated_texts.append(paragraph.text.strip())
                        
    # Save to BytesIO
    out_stream = io.BytesIO()
    doc.save(out_stream)
    
    # Encode to base64
    b64_data = base64.b64encode(out_stream.getvalue()).decode("utf-8")
    
    full_text = "\n\n".join(all_translated_texts)
    return full_text, b64_data


async def translate_txt_document(
    file_bytes: bytes,
    translate_fn: Callable[[str], Coroutine[None, None, str]]
) -> Tuple[str, str]:
    """
    Translates a TXT document line by line, preserving newlines.
    Returns:
        Tuple[str, str]: (translated_text, base64_encoded_txt)
    """
    # Decode input — try UTF-8 first, fallback to latin-1 for legacy files
    try:
        original_text = file_bytes.decode("utf-8-sig")  # utf-8-sig strips BOM if present
    except UnicodeDecodeError:
        original_text = file_bytes.decode("latin-1")
    
    lines = original_text.split("\n")
    
    translated_lines = []
    for line in lines:
        stripped_line = line.strip()
        if stripped_line:
            translated_lines.append(await translate_fn(stripped_line))
        else:
            translated_lines.append("")  # Preserve empty lines
            
    translated_text = "\n".join(translated_lines)
    
    # Encode with UTF-8 BOM so that Windows editors (Notepad, Word, etc.)
    # correctly detect the encoding and display Vietnamese characters properly.
    output_bytes = "\ufeff".encode("utf-8") + translated_text.encode("utf-8")
    b64_data = base64.b64encode(output_bytes).decode("utf-8")
    
    return translated_text, b64_data
