"""Add status column to file table

Revision ID: 13681f676df0
Revises: 0002_session_client_fields
Create Date: 2026-04-23 04:35:48.477420
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13681f676df0'
down_revision: Union[str, Sequence[str], None] = '0002_session_client_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('status', sa.Enum('pending', 'success', 'error', name='status_t'), nullable=False, server_default='pending'))
    op.add_column('file', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('file', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('file_session_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'session', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_segment_file_id_fkey'), 'file_segment', type_='foreignkey')
    op.create_foreign_key(None, 'file_segment', 'file', ['file_id'], ['file_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('logs_translation_id_fkey'), 'logs', type_='foreignkey')
    op.drop_constraint(op.f('logs_file_id_fkey'), 'logs', type_='foreignkey')
    op.drop_constraint(op.f('logs_session_id_fkey'), 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'translation', ['translation_id'], ['trans_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'logs', 'file', ['file_id'], ['file_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'logs', 'session', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.alter_column('session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('translation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('uniq_translation_cache'), table_name='translation')
    op.create_unique_constraint('uniq_translation_cache', 'translation', ['text_hash', 'source_lang', 'target_lang', 'domain_id'])
    op.drop_constraint(op.f('fk_translation_session'), 'translation', type_='foreignkey')
    op.create_foreign_key(None, 'translation', 'session', ['session_id'], ['session_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translation', type_='foreignkey')
    op.create_foreign_key(op.f('fk_translation_session'), 'translation', 'session', ['session_id'], ['session_id'])
    op.drop_constraint('uniq_translation_cache', 'translation', type_='unique')
    op.create_index(op.f('uniq_translation_cache'), 'translation', ['text_hash', 'source_lang', 'target_lang', 'domain_id'], unique=True)
    op.alter_column('translation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('session', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(op.f('logs_session_id_fkey'), 'logs', 'session', ['session_id'], ['session_id'])
    op.create_foreign_key(op.f('logs_file_id_fkey'), 'logs', 'file', ['file_id'], ['file_id'])
    op.create_foreign_key(op.f('logs_translation_id_fkey'), 'logs', 'translation', ['translation_id'], ['trans_id'])
    op.drop_constraint(None, 'file_segment', type_='foreignkey')
    op.create_foreign_key(op.f('file_segment_file_id_fkey'), 'file_segment', 'file', ['file_id'], ['file_id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_session_id_fkey'), 'file', 'session', ['session_id'], ['session_id'])
    op.alter_column('file', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('file', 'error_message')
    op.drop_column('file', 'status')
    # ### end Alembic commands ###
